--  criação da tabela categoria

CREATE TABLE public.categoria (
	id_categoria int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_categoria varchar(255) NULL,
	area_conhecimento varchar(255) NULL,
	descricao varchar(255) NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria),
	CONSTRAINT categoria_nome_categoria_key UNIQUE (nome_categoria)
);

-- inserção de dados

INSERT INTO Categoria (nome_categoria, area_conhecimento, descricao) VALUES
('Literatura Brasileira', 'Linguística, Letras e Artes', 'Obras de ficção e não-ficção de autores brasileiros, abrangendo diversos períodos e estilos, do Romantismo ao Contemporâneo.'),
('Distopia e Ficção Científica', 'Ciências Humanas e Sociais Aplicadas', 'Romances que exploram futuros hipotéticos, sociedades opressivas ou avanços tecnológicos (Ex: Aldous Huxley, George Orwell).'),
('Realismo Mágico', 'Linguística, Letras e Artes', 'Estilo literário que mescla elementos fantásticos e mitológicos com o cotidiano realista (Ex: Gabriel García Márquez).'),
('Literatura Russa Clássica', 'Linguística, Letras e Artes', 'Grandes obras da literatura russa do século XIX, com foco em temas morais, filosóficos e psicológicos (Ex: Fiódor Dostoiévski).'),
('Modernismo e Pós-Modernismo', 'Linguística, Letras e Artes', 'Obras que experimentam novas formas narrativas, fluxo de consciência e fragmentação (Ex: Virginia Woolf, Clarice Lispector).'),
('Ficção Japonesa Contemporânea', 'Linguística, Letras e Artes', 'Romances contemporâneos que frequentemente misturam surrealismo, cultura pop e temas existenciais (Ex: Haruki Murakami).'),
('Literatura Norte-Americana do Século XX', 'Linguística, Letras e Artes', 'Obras que capturam o "espírito" e a cultura americana moderna, frequentemente com um estilo direto e conciso (Ex: Ernest Hemingway, Toni Morrison).'),
('Romance de Costumes e Social', 'Linguística, Letras e Artes', 'Obras que retratam e criticam detalhadamente os costumes, hierarquias e relações sociais de uma época (Ex: Jane Austen, Machado de Assis).'),
('Filosofia Existencial e Absurdo', 'Ciências Humanas e Filosofia', 'Obras de ficção ou ensaios que exploram a condição humana, o significado da vida e o conceito de absurdo (Ex: Albert Camus).'),
('Contos e Ensaios Fantásticos', 'Linguística, Letras e Artes', 'Coleções de contos curtos e ensaios que lidam com metafísica, labirintos, bibliotecas e realidades alternativas (Ex: Jorge Luis Borges).');
