-- public.livro definição

-- Drop table

-- DROP TABLE public.livro;

CREATE TABLE public.livro (
	livro_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ano_publicacao int4 NULL,
	titulo varchar(255) NULL,
	url_arquivo varchar(255) NULL,
	autor_id int8 NULL,
	categoria_id int8 NULL,
	CONSTRAINT livro_pkey PRIMARY KEY (livro_id)
);


-- public.livro chaves estrangeiras

ALTER TABLE public.livro ADD CONSTRAINT fk823wf30ms4bomdmqk9xekpv6c FOREIGN KEY (categoria_id) REFERENCES public.categoria(categoria_id);
ALTER TABLE public.livro ADD CONSTRAINT fkrp0atct0grsplospsqqay36vy FOREIGN KEY (autor_id) REFERENCES public.autor(id_autor);