-- public.usuario definição

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	usuario_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	nome_completo varchar(100) NOT NULL,
	telefone varchar(255) NOT NULL,
	CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email),
	CONSTRAINT uk86phslelq64eeo6insr50y422 UNIQUE (telefone),
	CONSTRAINT usuario_pkey PRIMARY KEY (usuario_id)
);