--  criação da tabela livro

CREATE TABLE public.livro (
	id_livro int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_livro varchar(255) NULL,
	ano_publicacao int4 NULL,
	url_visualizacao varchar(1000) NULL,
	url_download varchar(1000) NULL,
	preco numeric(38, 2) NULL,
	id_autor int8 NULL,
	id_categoria int8 NULL,
	CONSTRAINT livro_pkey PRIMARY KEY (id_livro),
	CONSTRAINT livro_nome_livro_key UNIQUE (nome_livro)
);

--  criação de chaves estrangeiras

ALTER TABLE public.livro ADD CONSTRAINT fk7v25m35cptaoro3f0xq6chy37 FOREIGN KEY (id_autor) REFERENCES public.autor(id_autor);
ALTER TABLE public.livro ADD CONSTRAINT fksytxfd70p7l51i2cwndj1d21m FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria);

-- inserção de dados

INSERT INTO Livro (nome_livro, ano_publicacao, url_visualizacao, url_download, preco, id_autor, id_categoria) VALUES

-- Autor 1: Machado de Assis (ID 1) - Categoria 1: Literatura Brasileira
('Memórias Póstumas de Brás Cubas', 1881, 'http://visualizar.livros.vc/9788573264102', 'http://download.livros.vc/9788573264102.pdf', 29.90, 1, 1),
('Dom Casmurro', 1899, 'http://visualizar.livros.vc/9788573264096', 'http://download.livros.vc/9788573264096.pdf', 32.50, 1, 1),
('Quincas Borba', 1891, 'http://visualizar.livros.vc/9788573264126', 'http://download.livros.vc/9788573264126.pdf', 25.00, 1, 8),
('O Alienista', 1882, 'http://visualizar.livros.vc/9788573264133', 'http://download.livros.vc/9788573264133.pdf', 18.90, 1, 1),

-- Autor 2: Aldous Huxley (ID 2) - Categoria 2: Distopia e Ficção Científica
('Admirável Mundo Novo', 1932, 'http://visualizar.livros.vc/9788577990591', 'http://download.livros.vc/9788577990591.pdf', 45.99, 2, 2),
('A Ilha', 1962, 'http://visualizar.livros.vc/9788535914607', 'http://download.livros.vc/9788535914607.pdf', 38.00, 2, 2),
('As Portas da Percepção', 1954, 'http://visualizar.livros.vc/9788571649931', 'http://download.livros.vc/9788571649931.pdf', 27.90, 2, 9),

-- Autor 3: Ernest Hemingway (ID 3) - Categoria 7: Literatura Norte-Americana
('O Velho e o Mar', 1952, 'http://visualizar.livros.vc/9788571649948', 'http://download.livros.vc/9788571649948.pdf', 35.00, 3, 7),
('Por Quem os Sinos Dobram', 1940, 'http://visualizar.livros.vc/9788571649955', 'http://download.livros.vc/9788571649955.pdf', 49.90, 3, 7),
('O Sol Também se Levanta', 1926, 'http://visualizar.livros.vc/9788571649962', 'http://download.livros.vc/9788571649962.pdf', 42.00, 3, 7),

-- Autor 4: Fernando Sabino (ID 4) - Categoria 1: Literatura Brasileira
('O Encontro Marcado', 1956, 'http://visualizar.livros.vc/9788501004140', 'http://download.livros.vc/9788501004140.pdf', 31.90, 4, 1),
('A Mulher do Vizinho', 1962, 'http://visualizar.livros.vc/9788501004157', 'http://download.livros.vc/9788501004157.pdf', 26.50, 4, 1),

-- Autor 5: Jorge Luis Borges (ID 5) - Categoria 10: Contos e Ensaios Fantásticos
('Ficções', 1944, 'http://visualizar.livros.vc/9788535914270', 'http://download.livros.vc/9788535914270.pdf', 40.00, 5, 10),
('O Aleph', 1949, 'http://visualizar.livros.vc/9788535914287', 'http://download.livros.vc/9788535914287.pdf', 37.50, 5, 10),
('O Livro de Areia', 1975, 'http://visualizar.livros.vc/9788535914294', 'http://download.livros.vc/9788535914294.pdf', 34.90, 5, 10),

-- Autor 6: Jane Austen (ID 6) - Categoria 8: Romance de Costumes
('Orgulho e Preconceito', 1813, 'http://visualizar.livros.vc/9788537807759', 'http://download.livros.vc/9788537807759.pdf', 22.90, 6, 8),
('Razão e Sensibilidade', 1811, 'http://visualizar.livros.vc/9788537807766', 'http://download.livros.vc/9788537807766.pdf', 24.50, 6, 8),
('Emma', 1815, 'http://visualizar.livros.vc/9788537807773', 'http://download.livros.vc/9788537807773.pdf', 28.00, 6, 8),

-- Autor 7: Gabriel García Márquez (ID 7) - Categoria 3: Realismo Mágico
('Cem Anos de Solidão', 1967, 'http://visualizar.livros.vc/9788501014163', 'http://download.livros.vc/9788501014163.pdf', 55.00, 7, 3),
('O Amor nos Tempos do Cólera', 1985, 'http://visualizar.livros.vc/9788501014170', 'http://download.livros.vc/9788501014170.pdf', 48.90, 7, 3),
('Crônica de uma Morte Anunciada', 1981, 'http://visualizar.livros.vc/9788501014187', 'http://download.livros.vc/9788501014187.pdf', 33.50, 7, 3),

-- Autor 8: Virginia Woolf (ID 8) - Categoria 5: Modernismo e Pós-Modernismo
('Mrs. Dalloway', 1925, 'http://visualizar.livros.vc/9788535917455', 'http://download.livros.vc/9788535917455.pdf', 41.90, 8, 5),
('Ao Farol', 1927, 'http://visualizar.livros.vc/9788535917462', 'http://download.livros.vc/9788535917462.pdf', 39.90, 8, 5),
('Um Teto Todo Seu', 1929, 'http://visualizar.livros.vc/9788535917479', 'http://download.livros.vc/9788535917479.pdf', 21.90, 8, 5),

-- Autor 9: Albert Camus (ID 9) - Categoria 9: Filosofia Existencial e Absurdo
('O Estrangeiro', 1942, 'http://visualizar.livros.vc/9788501004201', 'http://download.livros.vc/9788501004201.pdf', 36.00, 9, 9),
('A Peste', 1947, 'http://visualizar.livros.vc/9788501004218', 'http://download.livros.vc/9788501004218.pdf', 44.90, 9, 9),
('O Mito de Sísifo', 1942, 'http://visualizar.livros.vc/9788501004225', 'http://download.livros.vc/9788501004225.pdf', 30.50, 9, 9),

-- Autor 10: Clarice Lispector (ID 10) - Categoria 5: Modernismo e Pós-Modernismo
('A Hora da Estrela', 1977, 'http://visualizar.livros.vc/9788532505508', 'http://download.livros.vc/9788532505508.pdf', 33.00, 10, 5),
('Perto do Coração Selvagem', 1943, 'http://visualizar.livros.vc/9788532505515', 'http://download.livros.vc/9788532505515.pdf', 35.50, 10, 5),
('Laços de Família', 1960, 'http://visualizar.livros.vc/9788532505522', 'http://download.livros.vc/9788532505522.pdf', 29.90, 10, 5),

-- Autor 11: Haruki Murakami (ID 11) - Categoria 6: Ficção Japonesa Contemporânea
('Kafka à Beira-Mar', 2002, 'http://visualizar.livros.vc/9788535914102', 'http://download.livros.vc/9788535914102.pdf', 59.90, 11, 6),
('Norwegian Wood', 1987, 'http://visualizar.livros.vc/9788535914119', 'http://download.livros.vc/9788535914119.pdf', 52.00, 11, 6),
('1Q84 (Livro 1)', 2009, 'http://visualizar.livros.vc/9788535914126', 'http://download.livros.vc/9788535914126.pdf', 65.50, 11, 6),
('Crônica do Pássaro de Corda', 1994, 'http://visualizar.livros.vc/9788535914133', 'http://download.livros.vc/9788535914133.pdf', 62.00, 11, 6),

-- Autor 12: Toni Morrison (ID 12) - Categoria 7: Literatura Norte-Americana
('Amada', 1987, 'http://visualizar.livros.vc/9788535915505', 'http://download.livros.vc/9788535915505.pdf', 47.90, 12, 7),
('O Olho Mais Azul', 1970, 'http://visualizar.livros.vc/9788535915512', 'http://download.livros.vc/9788535915512.pdf', 39.00, 12, 7),
('Jazz', 1992, 'http://visualizar.livros.vc/9788535915529', 'http://download.livros.vc/9788535915529.pdf', 43.50, 12, 7),

-- Autor 13: George Orwell (ID 13) - Categoria 2: Distopia e Ficção Científica
('1984', 1949, 'http://visualizar.livros.vc/9788520927909', 'http://download.livros.vc/9788520927909.pdf', 30.00, 13, 2),
('A Revolução dos Bichos', 1945, 'http://visualizar.livros.vc/9788520927916', 'http://download.livros.vc/9788520927916.pdf', 25.90, 13, 2),
('Na Pior em Paris e Londres', 1933, 'http://visualizar.livros.vc/9788520927923', 'http://download.livros.vc/9788520927923.pdf', 34.00, 13, 8),

-- Autor 14: Lygia Fagundes Telles (ID 14) - Categoria 1: Literatura Brasileira
('As Meninas', 1973, 'http://visualizar.livros.vc/9788535912900', 'http://download.livros.vc/9788535912900.pdf', 36.90, 14, 1),
('Ciranda de Pedra', 1954, 'http://visualizar.livros.vc/9788535912917', 'http://download.livros.vc/9788535912917.pdf', 31.00, 14, 1),
('Antes do Baile Verde', 1970, 'http://visualizar.livros.vc/9788535912924', 'http://download.livros.vc/9788535912924.pdf', 28.50, 14, 1),

-- Autor 15: Fiódor Dostoiévski (ID 15) - Categoria 4: Literatura Russa Clássica
('Crime e Castigo', 1866, 'http://visualizar.livros.vc/9788573264157', 'http://download.livros.vc/9788573264157.pdf', 58.00, 15, 4),
('Os Irmãos Karamazov', 1880, 'http://visualizar.livros.vc/9788573264164', 'http://download.livros.vc/9788573264164.pdf', 72.90, 15, 4),
('O Idiota', 1869, 'http://visualizar.livros.vc/9788573264171', 'http://download.livros.vc/9788573264171.pdf', 60.50, 15, 4),
('Memórias do Subsolo', 1864, 'http://visualizar.livros.vc/9788573264188', 'http://download.livros.vc/9788573264188.pdf', 27.00, 15, 4),

-- Livros adicionais para equilibrar
-- Autor 1: Machado de Assis (ID 1)
('Ressurreição', 1872, 'http://visualizar.livros.vc/9788573264195', 'http://download.livros.vc/9788573264195.pdf', 21.00, 1, 1),
('Esaú e Jacó', 1904, 'http://visualizar.livros.vc/9788573264201', 'http://download.livros.vc/9788573264201.pdf', 27.90, 1, 1),

-- Autor 5: Jorge Luis Borges (ID 5)
('História Universal da Infâmia', 1935, 'http://visualizar.livros.vc/9788535914300', 'http://download.livros.vc/9788535914300.pdf', 35.00, 5, 10),
('Evaristo Carriego', 1930, 'http://visualizar.livros.vc/9788535914317', 'http://download.livros.vc/9788535914317.pdf', 29.50, 5, 10),

-- Autor 8: Virginia Woolf (ID 8)
('Orlando', 1928, 'http://visualizar.livros.vc/9788535917486', 'http://download.livros.vc/9788535917486.pdf', 46.00, 8, 5),
('Flush', 1933, 'http://visualizar.livros.vc/9788535917493', 'http://download.livros.vc/9788535917493.pdf', 32.90, 8, 5),

-- Autor 10: Clarice Lispector (ID 10)
('Uma Aprendizagem ou O Livro dos Prazeres', 1969, 'http://visualizar.livros.vc/9788532505539', 'http://download.livros.vc/9788532505539.pdf', 38.00, 10, 5),
('Água Viva', 1973, 'http://visualizar.livros.vc/9788532505546', 'http://download.livros.vc/9788532505546.pdf', 37.50, 10, 5),

-- Autor 7: Gabriel García Márquez (ID 7)
('Ninguém Escreve ao Coronel', 1961, 'http://visualizar.livros.vc/9788501014194', 'http://download.livros.vc/9788501014194.pdf', 30.90, 7, 3),

-- Autor 13: George Orwell (ID 13)
('Homenagem à Catalunha', 1938, 'http://visualizar.livros.vc/9788520927930', 'http://download.livros.vc/9788520927930.pdf', 37.90, 13, 2),

-- Autor 15: Fiódor Dostoiévski (ID 15)
('Pobres Gente', 1846, 'http://visualizar.livros.vc/9788573264218', 'http://download.livros.vc/9788573264218.pdf', 45.00, 15, 4),

-- Autor 6: Jane Austen (ID 6)
('Persuasão', 1817, 'http://visualizar.livros.vc/9788537807780', 'http://download.livros.vc/9788537807780.pdf', 26.90, 6, 8),

-- Autor 3: Ernest Hemingway (ID 3)
('Adeus às Armas', 1929, 'http://visualizar.livros.vc/9788571649979', 'http://download.livros.vc/9788571649979.pdf', 48.00, 3, 7),

-- Autor 11: Haruki Murakami (ID 11)
('Minha Querida Sputnik', 1999, 'http://visualizar.livros.vc/9788535914140', 'http://download.livros.vc/9788535914140.pdf', 50.00, 11, 6),

-- Autor 12: Toni Morrison (ID 12)
('Paraíso', 1997, 'http://visualizar.livros.vc/9788535915536', 'http://download.livros.vc/9788535915536.pdf', 45.00, 12, 7),

-- Livros para completar os 50
('O Drible', 2013, 'http://visualizar.livros.vc/9788535912931', 'http://download.livros.vc/9788535912931.pdf', 39.90, 14, 1), -- Lygia Fagundes Telles
('Um Certo Sorriso', 1956, 'http://visualizar.livros.vc/9788501004232', 'http://download.livros.vc/9788501004232.pdf', 31.00, 9, 9), -- Albert Camus
('Contos de Canterbury (seleção)', 1938, 'http://visualizar.livros.vc/9788571649986', 'http://download.livros.vc/9788571649986.pdf', 38.90, 3, 7), -- Ernest Hemingway
('Contraponto', 1928, 'http://visualizar.livros.vc/9788577990607', 'http://download.livros.vc/9788577990607.pdf', 40.00, 2, 2), -- Aldous Huxley
('O Fim do Mundo e o Impiedoso País das Maravilhas', 1985, 'http://visualizar.livros.vc/9788535914157', 'http://download.livros.vc/9788535914157.pdf', 55.00, 11, 6), -- Haruki Murakami
('O Duplo', 1846, 'http://visualizar.livros.vc/9788573264225', 'http://download.livros.vc/9788573264225.pdf', 42.00, 15, 4), -- Fiódor Dostoiévski
('Um Outro Olhar', 1974, 'http://visualizar.livros.vc/9788501004164', 'http://download.livros.vc/9788501004164.pdf', 24.50, 4, 1), -- Fernando Sabino
('Helena', 1876, 'http://visualizar.livros.vc/9788573264232', 'http://download.livros.vc/9788573264232.pdf', 23.00, 1, 1), -- Machado de Assis
('Sentido e Sensibilidade', 1811, 'http://visualizar.livros.vc/9788537807797', 'http://download.livros.vc/9788537807797.pdf', 25.00, 6, 8), -- Jane Austen
('As Ondas', 1931, 'http://visualizar.livros.vc/9788535917509', 'http://download.livros.vc/9788535917509.pdf', 43.00, 8, 5), -- Virginia Woolf
('O Outro', 1975, 'http://visualizar.livros.vc/9788535914324', 'http://download.livros.vc/9788535914324.pdf', 33.00, 5, 10), -- Jorge Luis Borges
('Canção de Salomão', 1977, 'http://visualizar.livros.vc/9788535915543', 'http://download.livros.vc/9788535915543.pdf', 49.00, 12, 7); -- Toni Morrison
