-- public.categoria definição

-- Drop table

-- DROP TABLE public.categoria;

CREATE TABLE public.categoria (
	categoria_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	area_conhecimento varchar(255) NULL,
	descricao varchar(255) NULL,
	nome varchar(255) NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (categoria_id),
	CONSTRAINT ukprx5elpv558ah8pk8x18u56yc UNIQUE (nome)
);