-- public.autor definição

-- Drop table

-- DROP TABLE public.autor;

CREATE TABLE public.autor (
	id_autor int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	biografia varchar(255) NULL,
	data_nascimento date NULL,
	nacionalidade varchar(255) NULL,
	nome_autor varchar(100) NOT NULL,
	CONSTRAINT autor_pkey PRIMARY KEY (id_autor)
);