-- public.historico_chat definição

-- Drop table

-- DROP TABLE public.historico_chat;

CREATE TABLE public.historico_chat (
	session_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	horario timestamp(6) NULL,
	message varchar(255) NULL,
	message_id varchar(255) NULL,
	usuario_id int8 NULL,
	CONSTRAINT historico_chat_pkey PRIMARY KEY (session_id)
);


-- public.historico_chat chaves estrangeiras

ALTER TABLE public.historico_chat ADD CONSTRAINT fkffxnwwngyhpajyovov8jtqhw8 FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);