--  criação da tabela autor

CREATE TABLE public.autor (
	id_autor int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_autor varchar(100) NOT NULL,
	data_nascimento date NULL,
	nacionalidade varchar(255) NULL,
	biografia varchar(1000) NULL,
	CONSTRAINT autor_pkey PRIMARY KEY (id_autor)
);

-- inserção de dados

INSERT INTO Autor (nome_autor, data_nascimento, nacionalidade, biografia) VALUES
('Machado de Assis', '1839-06-21', 'Brasileira', 'https://pt.wikipedia.org/wiki/Machado_de_Assis'), --
('Aldous Huxley', '1894-07-26', 'Britânica', 'https://pt.wikipedia.org/wiki/Aldous_Huxley'), --
('Ernest Hemingway', '1899-07-21', 'Norte-americana', 'https://pt.wikipedia.org/wiki/Ernest_Hemingway'), --
('Fernando Sabino', '1923-10-12', 'Brasileira', 'https://pt.wikipedia.org/wiki/Fernando_Sabino'), --
('Jorge Luis Borges', '1899-08-24', 'Argentina', 'https://pt.wikipedia.org/wiki/Jorge_Luis_Borges'), -- Data de nascimento padrão da Wikipedia
('Jane Austen', '1775-12-16', 'Inglesa', 'https://pt.wikipedia.org/wiki/Jane_Austen'), --
('Gabriel García Márquez', '1927-03-06', 'Colombiana', 'https://pt.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez'), --
('Virginia Woolf', '1882-01-25', 'Britânica', 'https://pt.wikipedia.org/wiki/Virginia_Woolf'), --
('Albert Camus', '1913-11-07', 'Francesa (nascido na Argélia)', 'https://pt.wikipedia.org/wiki/Albert_Camus'), --
('Clarice Lispector', '1920-12-10', 'Brasileira (nascida na Ucrânia)', 'https://pt.wikipedia.org/wiki/Clarice_Lispector'), --
('Haruki Murakami', '1949-01-12', 'Japonesa', 'https://pt.wikipedia.org/wiki/Haruki_Murakami'), --
('Toni Morrison', '1931-02-18', 'Norte-americana', 'https://pt.wikipedia.org/wiki/Toni_Morrison'), --
('George Orwell', '1903-06-25', 'Britânica', 'https://pt.wikipedia.org/wiki/George_Orwell'), --
('Lygia Fagundes Telles', '1923-04-19', 'Brasileira', 'https://pt.wikipedia.org/wiki/Lygia_Fagundes_Telles'), --
('Fiódor Dostoiévski', '1821-11-11', 'Russa', 'https://pt.wikipedia.org/wiki/Fiódor_Dostoiévski'); --
