--  criação da tabela usuario

CREATE TABLE public.usuario (
	id_usuario int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_usuario varchar(100) NOT NULL,
	email varchar(255) NOT NULL,
	telefone varchar(255) NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
	CONSTRAINT usuario_email_key UNIQUE (email)
);

-- inserção de dados

INSERT INTO Usuario (nome_usuario, email, telefone) VALUES
('Ana Clara da Silva', 'ana.silva@exemplo.com.br', '(11) 98765-4321'),
('Bruno Eduardo Mendes', 'bruno.mendes@exemplo.com.br', '(21) 99876-5432'),
('Carla Souza Lima', 'carla.lima@exemplo.com.br', '(31) 97654-3210'),
('Daniela Ferreira Rocha', 'daniela.rocha@exemplo.com.br', '(85) 99988-7766'),
('Emerson Santos Oliveira', 'emerson.santos@exemplo.com.br', '(61) 98877-6655');