--  criação da tabela historico_chat

CREATE TABLE public.historico_chat (
	id_session int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_message varchar(255) NULL,
	message varchar(255) NULL,
	horario timestamp(6) NULL,
	CONSTRAINT historico_chat_pkey PRIMARY KEY (id_session)
);